feat: Updated web workflow to streamline image building

diff --git a/.github/workflows/build-web.yml b/.github/workflows/build-web.yml
--- a/.github/workflows/build-web.yml
+++ b/.github/workflows/build-web.yml
@@ -39,22 +39,45 @@ jobs:
         with:
           version: 8.9.0
           run_install: true
-          
-      - name: Build, tag, and push image to Github container registry
-        id: build-image
+
+      - name: Log in to GitHub Container Registry
+        run: echo $GH_PASSWORD | docker login ghcr.io -u $GH_ACTOR --password-stdin
+
+      - name: Build & Tag Docker image
         env:
           REGISTERY_OWNER: implerhq
           DOCKER_NAME: impler/web
           IMAGE_TAG: ${{ github.event.pull_request.head.sha || github.sha }}
-          GH_ACTOR: implerhq
-          GH_PASSWORD: ${{ secrets.GH_PACKAGES }}
         run: |
-          echo $GH_PASSWORD | docker login ghcr.io -u $GH_ACTOR --password-stdin 
           docker build -t ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:$IMAGE_TAG -f apps/web/Dockerfile .
-          # docker tag ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:$IMAGE_TAG ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:prod
           docker tag ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:$IMAGE_TAG ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:latest
 
-          # docker push ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:prod
+      - name: Run Docker container
+        env:
+          REGISTERY_OWNER: implerhq
+          DOCKER_NAME: impler/web
+          IMAGE_TAG: ${{ github.event.pull_request.head.sha || github.sha }}
+        run: docker run --network=host -dit ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:$IMAGE_TAG
+
+      - name: Check application health
+        run: |
+          for i in {1..5}; do
+            if curl --output /dev/null --silent --head --fail http://localhost:4200; then
+              echo "Application is up!"
+              exit 0
+            fi
+            echo "Waiting for the application to start..."
+            sleep 5
+          done
+          echo "Application failed to start"
+          exit 1
+
+      - name: Push Docker image
+        env:
+          REGISTERY_OWNER: implerhq
+          DOCKER_NAME: impler/web
+          IMAGE_TAG: ${{ github.event.pull_request.head.sha || github.sha }}
+        run: |
           docker push ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:latest
           docker push ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:$IMAGE_TAG
           echo "::set-output name=IMAGE::ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:$IMAGE_TAG"
