env updated3

diff --git a/.github/workflows/build-api.yml b/.github/workflows/build-api.yml
--- a/.github/workflows/build-api.yml
+++ b/.github/workflows/build-api.yml
@@ -51,9 +51,9 @@ jobs:
           DOCKER_NAME: impler/api
           IMAGE_TAG: ${{ github.sha }}
           GH_ACTOR: implerhq
-          GH_PASSWORD: ${{ secrets.GH_PACKAGES }}
+          GH_PASSWORD: ${{ secrets.DEMO_SECRET }}
         run: |
-          [ -z "${{ secrets.GH_PACKAGES }}" ] && { echo "Error: GH_PASSWORD is not set"; exit 1; }
+          [ -z "$GH_PASSWORD" ] && { echo "Error: GH_PASSWORD is not set"; exit 1; }
           echo $GH_PASSWORD | docker login ghcr.io -u $GH_ACTOR --password-stdin
           docker build -t ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:$IMAGE_TAG -f apps/api/Dockerfile .
           docker tag ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:$IMAGE_TAG ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:latest
